<?php

use App\Models\Master\RefJabatan;
use App\Models\Master\RefTicketCategory;
use App\Models\Master\RefTicketSla;
use App\Models\Master\RefUnit;
use App\Models\Master\RolePermission;
use App\Models\Master\SysAction;
use App\Models\Master\SysModule;
use App\Models\Master\SysPermission;
use App\Models\Master\SysRole;
use App\Models\Master\SysUser;

$active = ['type' => 'boolean', 'label' => 'Active'];
$description = ['type' => 'textarea', 'label' => 'Description', 'span' => 2];

return [
    'units' => [
        'title' => 'Unit Organisasi',
        'subtitle' => 'Hirarki parent-child unit organisasi',
        'group' => 'Master Organisasi',
        'icon' => 'bi-diagram-3',
        'model' => RefUnit::class,
        'route' => 'master.units',
        'with' => ['parent'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'parent.name', 'label' => 'Parent Unit'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'parent_id' => ['type' => 'select', 'label' => 'Parent Unit', 'relation' => 'units', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'parent_id' => ['nullable', 'exists:ref_units,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_units,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'jabatan' => [
        'title' => 'Jabatan',
        'subtitle' => 'Level jabatan dan posisi organisasi',
        'group' => 'Master Organisasi',
        'icon' => 'bi-person-vcard',
        'model' => RefJabatan::class,
        'route' => 'master.jabatan',
        'with' => ['unit'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'unit.name', 'label' => 'Unit'],
            ['key' => 'level', 'label' => 'Level'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'unit_id' => ['type' => 'select', 'label' => 'Unit', 'relation' => 'units', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'level' => ['type' => 'number', 'label' => 'Level'],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'unit_id' => ['nullable', 'exists:ref_units,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_jabatan,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'level' => ['required', 'integer', 'min:1'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'users' => [
        'title' => 'Users',
        'subtitle' => 'User ERP, unit kerja, jabatan, dan status aktif',
        'group' => 'Users & Access',
        'icon' => 'bi-people',
        'model' => SysUser::class,
        'route' => 'master.users',
        'with' => ['unit', 'jabatan', 'roles'],
        'display' => 'name',
        'columns' => [
            ['key' => 'employee_no', 'label' => 'Employee No'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'username', 'label' => 'Username'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'unit.name', 'label' => 'Unit'],
            ['key' => 'jabatan.name', 'label' => 'Jabatan'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'unit_id' => ['type' => 'select', 'label' => 'Unit', 'relation' => 'units'],
            'jabatan_id' => ['type' => 'select', 'label' => 'Jabatan', 'relation' => 'jabatan'],
            'employee_no' => ['type' => 'text', 'label' => 'Employee No'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'email' => ['type' => 'email', 'label' => 'Email'],
            'username' => ['type' => 'text', 'label' => 'Username'],
            'password' => ['type' => 'password', 'label' => 'Password', 'hide_on_show' => true],
            'phone' => ['type' => 'text', 'label' => 'Phone'],
            'role_ids' => ['type' => 'multi_select', 'label' => 'Roles', 'relation' => 'roles', 'span' => 2],
            'is_active' => $active,
        ],
        'rules' => [
            'unit_id' => ['required', 'exists:ref_units,id'],
            'jabatan_id' => ['required', 'exists:ref_jabatan,id'],
            'employee_no' => ['required', 'string', 'max:50', 'unique:sys_users,employee_no,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'email', 'max:150', 'unique:sys_users,email,{id}'],
            'username' => ['required', 'string', 'max:80', 'unique:sys_users,username,{id}'],
            'password' => ['required_on_create', 'nullable', 'string', 'min:8'],
            'phone' => ['nullable', 'string', 'max:50'],
            'photo' => ['nullable', 'image', 'max:2048'],
            'role_ids' => ['nullable', 'array'],
            'role_ids.*' => ['exists:sys_roles,id'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'modules' => [
        'title' => 'Master Modules',
        'subtitle' => 'Application module catalog for dynamic permission generation',
        'group' => 'Users & Access',
        'icon' => 'bi-grid',
        'model' => SysModule::class,
        'route' => 'master.modules',
        'display' => 'name',
        'columns' => [
            ['key' => 'name', 'label' => 'Module'],
            ['key' => 'slug', 'label' => 'Slug'],
            ['key' => 'sort_no', 'label' => 'Sort'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'name' => ['type' => 'text', 'label' => 'Name'],
            'slug' => ['type' => 'text', 'label' => 'Slug'],
            'icon' => ['type' => 'text', 'label' => 'Icon'],
            'sort_no' => ['type' => 'number', 'label' => 'Sort No'],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'name' => ['required', 'string', 'max:150'],
            'slug' => ['required', 'string', 'max:100', 'unique:sys_modules,slug,{id}'],
            'icon' => ['nullable', 'string', 'max:80'],
            'sort_no' => ['nullable', 'integer', 'min:0'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'actions' => [
        'title' => 'Master Actions',
        'subtitle' => 'Reusable business actions for dynamic permission columns',
        'group' => 'Users & Access',
        'icon' => 'bi-lightning-charge',
        'model' => SysAction::class,
        'route' => 'master.actions',
        'display' => 'name',
        'columns' => [
            ['key' => 'name', 'label' => 'Action'],
            ['key' => 'slug', 'label' => 'Slug'],
            ['key' => 'sort_no', 'label' => 'Sort'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'name' => ['type' => 'text', 'label' => 'Name'],
            'slug' => ['type' => 'text', 'label' => 'Slug'],
            'sort_no' => ['type' => 'number', 'label' => 'Sort No'],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'name' => ['required', 'string', 'max:100'],
            'slug' => ['required', 'string', 'max:80', 'unique:sys_actions,slug,{id}'],
            'sort_no' => ['nullable', 'integer', 'min:0'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'roles' => [
        'title' => 'Roles',
        'subtitle' => 'Role akses aplikasi',
        'group' => 'Users & Access',
        'icon' => 'bi-shield-check',
        'model' => SysRole::class,
        'route' => 'master.roles',
        'display' => 'name',
        'with' => ['permissions'],
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description, 'is_active' => $active],
        'rules' => ['code' => ['required', 'string', 'max:50', 'unique:sys_roles,code,{id}'], 'name' => ['required', 'string', 'max:150'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'permissions' => [
        'title' => 'Permissions',
        'subtitle' => 'Permission granular per module',
        'group' => 'Users & Access',
        'icon' => 'bi-key',
        'model' => SysPermission::class,
        'route' => 'master.permissions',
        'with' => ['module', 'action'],
        'display' => 'permission_slug',
        'columns' => [['key' => 'module.name', 'label' => 'Module'], ['key' => 'action.name', 'label' => 'Action'], ['key' => 'permission_slug', 'label' => 'Permission Slug'], ['key' => 'permission_name', 'label' => 'Label']],
        'fields' => ['module_id' => ['type' => 'select', 'label' => 'Module', 'relation' => 'modules'], 'action_id' => ['type' => 'select', 'label' => 'Action', 'relation' => 'actions'], 'permission_name' => ['type' => 'text', 'label' => 'Label', 'span' => 2]],
        'rules' => ['module_id' => ['required', 'exists:sys_modules,id'], 'action_ids' => ['required', 'array'], 'action_ids.*' => ['exists:sys_actions,id']],
    ],
    'role-permissions' => [
        'title' => 'Role Permissions',
        'subtitle' => 'Mapping role dengan permission',
        'group' => 'Users & Access',
        'icon' => 'bi-diagram-2',
        'model' => RolePermission::class,
        'route' => 'master.role-permissions',
        'with' => ['role', 'permission'],
        'display' => 'id',
        'columns' => [['key' => 'role.name', 'label' => 'Role'], ['key' => 'permission.module', 'label' => 'Module'], ['key' => 'permission.name', 'label' => 'Permission']],
        'fields' => ['role_id' => ['type' => 'select', 'label' => 'Role', 'relation' => 'roles'], 'permission_id' => ['type' => 'select', 'label' => 'Permission', 'relation' => 'permissions']],
        'rules' => ['role_id' => ['required', 'exists:sys_roles,id'], 'permission_id' => ['required', 'exists:sys_permissions,id']],
    ],
    'ticket-categories' => [
        'title' => 'Ticket Categories',
        'subtitle' => 'Kategori tiket, hirarki parent-child, warna, icon, dan SLA default',
        'group' => 'Master Ticketing',
        'icon' => 'bi-ticket-perforated',
        'model' => RefTicketCategory::class,
        'route' => 'master-ticketing.categories',
        'with' => ['parent', 'sla'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'parent.name', 'label' => 'Parent'],
            ['key' => 'sla.name', 'label' => 'SLA'],
            ['key' => 'sort_no', 'label' => 'Sort No'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'parent_id' => ['type' => 'select', 'label' => 'Parent Category', 'relation' => 'ticket-categories', 'nullable' => true],
            'sla_id' => ['type' => 'select', 'label' => 'Ticket SLA', 'relation' => 'ticket-slas', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'color' => ['type' => 'color', 'label' => 'Color'],
            'icon' => ['type' => 'text', 'label' => 'Icon'],
            'sort_no' => ['type' => 'number', 'label' => 'Sort No'],
            'is_active' => $active,
        ],
        'rules' => [
            'parent_id' => ['nullable', 'exists:ref_ticket_categories,id'],
            'sla_id' => ['nullable', 'exists:ref_ticket_slas,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_ticket_categories,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'color' => ['nullable', 'string', 'max:30'],
            'icon' => ['nullable', 'string', 'max:80'],
            'sort_no' => ['nullable', 'numeric'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'ticket-slas' => [
        'title' => 'Ticket SLA',
        'subtitle' => 'Target response, resolve, dan eskalasi berdasarkan priority',
        'group' => 'Master Ticketing',
        'icon' => 'bi-stopwatch',
        'model' => RefTicketSla::class,
        'route' => 'master-ticketing.slas',
        'display' => 'name',
        'columns' => [
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'priority', 'label' => 'Priority'],
            ['key' => 'response_minutes', 'label' => 'Response (Minutes)'],
            ['key' => 'resolve_minutes', 'label' => 'Resolve (Minutes)'],
            ['key' => 'escalation_minutes', 'label' => 'Escalation (Minutes)'],
        ],
        'fields' => [
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'priority' => ['type' => 'select_static', 'label' => 'Priority', 'filter' => true, 'options' => ['low' => 'Low', 'medium' => 'Medium', 'high' => 'High', 'critical' => 'Critical']],
            'response_minutes' => ['type' => 'number', 'label' => 'Response Minutes'],
            'resolve_minutes' => ['type' => 'number', 'label' => 'Resolve Minutes'],
            'escalation_minutes' => ['type' => 'number', 'label' => 'Escalation Minutes'],
            'description' => $description,
        ],
        'rules' => [
            'name' => ['required', 'string', 'max:150'],
            'priority' => ['required', 'string', 'max:50'],
            'response_minutes' => ['required', 'numeric', 'min:0'],
            'resolve_minutes' => ['required', 'numeric', 'min:0'],
            'escalation_minutes' => ['nullable', 'numeric', 'min:0'],
            'description' => ['nullable', 'string'],
        ],
    ],
];
