<?php

use App\Models\Master\RefCostCode;
use App\Models\Master\RefItem;
use App\Models\Master\RefItemCategory;
use App\Models\Master\RefItemUnit;
use App\Models\Master\RefJabatan;
use App\Models\Master\RefProject;
use App\Models\Master\RefProjectSite;
use App\Models\Master\RefTicketCategory;
use App\Models\Master\RefTicketSla;
use App\Models\Master\RefUnit;
use App\Models\Master\RefVendor;
use App\Models\Master\RefVendorType;
use App\Models\Master\RolePermission;
use App\Models\Master\SysPermission;
use App\Models\Master\SysRole;
use App\Models\Master\SysUser;

$active = ['type' => 'boolean', 'label' => 'Active'];
$description = ['type' => 'textarea', 'label' => 'Description', 'span' => 2];

return [
    'units' => [
        'title' => 'Unit Organisasi',
        'subtitle' => 'Hirarki parent-child unit organisasi',
        'group' => 'Master Organisasi',
        'icon' => 'bi-diagram-3',
        'model' => RefUnit::class,
        'route' => 'master.units',
        'with' => ['parent'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'parent.name', 'label' => 'Parent Unit'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'parent_id' => ['type' => 'select', 'label' => 'Parent Unit', 'relation' => 'units', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'parent_id' => ['nullable', 'exists:ref_units,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_units,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'jabatan' => [
        'title' => 'Jabatan',
        'subtitle' => 'Level jabatan dan posisi organisasi',
        'group' => 'Master Organisasi',
        'icon' => 'bi-person-vcard',
        'model' => RefJabatan::class,
        'route' => 'master.jabatan',
        'with' => ['unit'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'unit.name', 'label' => 'Unit'],
            ['key' => 'level', 'label' => 'Level'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'unit_id' => ['type' => 'select', 'label' => 'Unit', 'relation' => 'units', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'level' => ['type' => 'number', 'label' => 'Level'],
            'description' => $description,
            'is_active' => $active,
        ],
        'rules' => [
            'unit_id' => ['nullable', 'exists:ref_units,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_jabatan,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'level' => ['required', 'integer', 'min:1'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'users' => [
        'title' => 'Users',
        'subtitle' => 'User ERP, unit kerja, jabatan, dan status aktif',
        'group' => 'Users & Akses',
        'icon' => 'bi-people',
        'model' => SysUser::class,
        'route' => 'master.users',
        'with' => ['unit', 'jabatan'],
        'display' => 'name',
        'columns' => [
            ['key' => 'employee_no', 'label' => 'Employee No'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'username', 'label' => 'Username'],
            ['key' => 'unit.name', 'label' => 'Unit'],
            ['key' => 'jabatan.name', 'label' => 'Jabatan'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'unit_id' => ['type' => 'select', 'label' => 'Unit', 'relation' => 'units'],
            'jabatan_id' => ['type' => 'select', 'label' => 'Jabatan', 'relation' => 'jabatan'],
            'employee_no' => ['type' => 'text', 'label' => 'Employee No'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'email' => ['type' => 'email', 'label' => 'Email'],
            'username' => ['type' => 'text', 'label' => 'Username'],
            'password' => ['type' => 'password', 'label' => 'Password', 'hide_on_show' => true],
            'phone' => ['type' => 'text', 'label' => 'Phone'],
            'is_active' => $active,
        ],
        'rules' => [
            'unit_id' => ['required', 'exists:ref_units,id'],
            'jabatan_id' => ['required', 'exists:ref_jabatan,id'],
            'employee_no' => ['required', 'string', 'max:50', 'unique:sys_users,employee_no,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'email', 'max:150', 'unique:sys_users,email,{id}'],
            'username' => ['required', 'string', 'max:80', 'unique:sys_users,username,{id}'],
            'password' => ['required_on_create', 'nullable', 'string', 'min:8'],
            'phone' => ['nullable', 'string', 'max:50'],
            'photo' => ['nullable', 'image', 'max:2048'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'roles' => [
        'title' => 'Roles',
        'subtitle' => 'Role akses aplikasi',
        'group' => 'Users & Akses',
        'icon' => 'bi-shield-check',
        'model' => SysRole::class,
        'route' => 'master.roles',
        'display' => 'name',
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description, 'is_active' => $active],
        'rules' => ['code' => ['required', 'string', 'max:50', 'unique:sys_roles,code,{id}'], 'name' => ['required', 'string', 'max:150'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'permissions' => [
        'title' => 'Permissions',
        'subtitle' => 'Permission granular per module',
        'group' => 'Users & Akses',
        'icon' => 'bi-key',
        'model' => SysPermission::class,
        'route' => 'master.permissions',
        'display' => 'name',
        'columns' => [['key' => 'module', 'label' => 'Module'], ['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name']],
        'fields' => ['module' => ['type' => 'text', 'label' => 'Module'], 'code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description],
        'rules' => ['module' => ['required', 'string', 'max:100'], 'code' => ['required', 'string', 'max:100', 'unique:sys_permissions,code,{id}'], 'name' => ['required', 'string', 'max:150'], 'description' => ['nullable', 'string']],
    ],
    'role-permissions' => [
        'title' => 'Role Permissions',
        'subtitle' => 'Mapping role dengan permission',
        'group' => 'Users & Akses',
        'icon' => 'bi-diagram-2',
        'model' => RolePermission::class,
        'route' => 'master.role-permissions',
        'with' => ['role', 'permission'],
        'display' => 'id',
        'columns' => [['key' => 'role.name', 'label' => 'Role'], ['key' => 'permission.module', 'label' => 'Module'], ['key' => 'permission.name', 'label' => 'Permission']],
        'fields' => ['role_id' => ['type' => 'select', 'label' => 'Role', 'relation' => 'roles'], 'permission_id' => ['type' => 'select', 'label' => 'Permission', 'relation' => 'permissions']],
        'rules' => ['role_id' => ['required', 'exists:sys_roles,id'], 'permission_id' => ['required', 'exists:sys_permissions,id']],
    ],
    'ticket-categories' => [
        'title' => 'Ticket Categories',
        'subtitle' => 'Kategori tiket, hirarki parent-child, warna, icon, dan SLA default',
        'group' => 'Master Ticketing',
        'icon' => 'bi-ticket-perforated',
        'model' => RefTicketCategory::class,
        'route' => 'master-ticketing.categories',
        'with' => ['parent', 'sla'],
        'display' => 'name',
        'columns' => [
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'parent.name', 'label' => 'Parent'],
            ['key' => 'sla.name', 'label' => 'SLA'],
            ['key' => 'sort_no', 'label' => 'Sort No'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'status'],
        ],
        'fields' => [
            'parent_id' => ['type' => 'select', 'label' => 'Parent Category', 'relation' => 'ticket-categories', 'nullable' => true],
            'sla_id' => ['type' => 'select', 'label' => 'Ticket SLA', 'relation' => 'ticket-slas', 'nullable' => true],
            'code' => ['type' => 'text', 'label' => 'Code'],
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'color' => ['type' => 'color', 'label' => 'Color'],
            'icon' => ['type' => 'text', 'label' => 'Icon'],
            'sort_no' => ['type' => 'number', 'label' => 'Sort No'],
            'is_active' => $active,
        ],
        'rules' => [
            'parent_id' => ['nullable', 'exists:ref_ticket_categories,id'],
            'sla_id' => ['nullable', 'exists:ref_ticket_slas,id'],
            'code' => ['required', 'string', 'max:50', 'unique:ref_ticket_categories,code,{id}'],
            'name' => ['required', 'string', 'max:150'],
            'color' => ['nullable', 'string', 'max:30'],
            'icon' => ['nullable', 'string', 'max:80'],
            'sort_no' => ['nullable', 'numeric'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'ticket-slas' => [
        'title' => 'Ticket SLA',
        'subtitle' => 'Target response, resolve, dan eskalasi berdasarkan priority',
        'group' => 'Master Ticketing',
        'icon' => 'bi-stopwatch',
        'model' => RefTicketSla::class,
        'route' => 'master-ticketing.slas',
        'display' => 'name',
        'columns' => [
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'priority', 'label' => 'Priority'],
            ['key' => 'response_minutes', 'label' => 'Response (Minutes)'],
            ['key' => 'resolve_minutes', 'label' => 'Resolve (Minutes)'],
            ['key' => 'escalation_minutes', 'label' => 'Escalation (Minutes)'],
        ],
        'fields' => [
            'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2],
            'priority' => ['type' => 'select_static', 'label' => 'Priority', 'filter' => true, 'options' => ['low' => 'Low', 'medium' => 'Medium', 'high' => 'High', 'critical' => 'Critical']],
            'response_minutes' => ['type' => 'number', 'label' => 'Response Minutes'],
            'resolve_minutes' => ['type' => 'number', 'label' => 'Resolve Minutes'],
            'escalation_minutes' => ['type' => 'number', 'label' => 'Escalation Minutes'],
            'description' => $description,
        ],
        'rules' => [
            'name' => ['required', 'string', 'max:150'],
            'priority' => ['required', 'string', 'max:50'],
            'response_minutes' => ['required', 'numeric', 'min:0'],
            'resolve_minutes' => ['required', 'numeric', 'min:0'],
            'escalation_minutes' => ['nullable', 'numeric', 'min:0'],
            'description' => ['nullable', 'string'],
        ],
    ],
    'item-categories' => [
        'title' => 'Item Categories',
        'subtitle' => 'Hirarki kategori item/material',
        'group' => 'Item / Material',
        'icon' => 'bi-tags',
        'model' => RefItemCategory::class,
        'route' => 'master.item-categories',
        'with' => ['parent'],
        'display' => 'name',
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name'], ['key' => 'parent.name', 'label' => 'Parent'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['parent_id' => ['type' => 'select', 'label' => 'Parent Category', 'relation' => 'item-categories', 'nullable' => true], 'code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description, 'is_active' => $active],
        'rules' => ['parent_id' => ['nullable', 'exists:ref_item_categories,id'], 'code' => ['required', 'string', 'max:50', 'unique:ref_item_categories,code,{id}'], 'name' => ['required', 'string', 'max:150'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'item-units' => [
        'title' => 'Item Units',
        'subtitle' => 'Satuan item/material',
        'group' => 'Item / Material',
        'icon' => 'bi-rulers',
        'model' => RefItemUnit::class,
        'route' => 'master.item-units',
        'display' => 'name',
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name']],
        'fields' => ['code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description],
        'rules' => ['code' => ['required', 'string', 'max:50', 'unique:ref_item_unit,code,{id}'], 'name' => ['required', 'string', 'max:100'], 'description' => ['nullable', 'string']],
    ],
    'items' => [
        'title' => 'Items / Material',
        'subtitle' => 'Master material konstruksi',
        'group' => 'Item / Material',
        'icon' => 'bi-box',
        'model' => RefItem::class,
        'route' => 'master.items',
        'with' => ['category', 'unit'],
        'display' => 'item_name',
        'columns' => [['key' => 'item_code', 'label' => 'Item Code'], ['key' => 'item_name', 'label' => 'Item Name'], ['key' => 'category.name', 'label' => 'Category'], ['key' => 'unit.name', 'label' => 'Unit'], ['key' => 'minimum_stock', 'label' => 'Min Stock'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['category_id' => ['type' => 'select', 'label' => 'Category', 'relation' => 'item-categories'], 'unit_id' => ['type' => 'select', 'label' => 'Unit', 'relation' => 'item-units'], 'item_code' => ['type' => 'text', 'label' => 'Item Code'], 'item_name' => ['type' => 'text', 'label' => 'Item Name', 'span' => 2], 'specification' => ['type' => 'textarea', 'label' => 'Specification', 'span' => 2], 'minimum_stock' => ['type' => 'number', 'label' => 'Minimum Stock', 'step' => '0.0001'], 'is_active' => $active],
        'rules' => ['category_id' => ['required', 'exists:ref_item_categories,id'], 'unit_id' => ['required', 'exists:ref_item_unit,id'], 'item_code' => ['required', 'string', 'max:50', 'unique:ref_items,item_code,{id}'], 'item_name' => ['required', 'string', 'max:180'], 'specification' => ['nullable', 'string'], 'minimum_stock' => ['nullable', 'numeric', 'min:0'], 'is_active' => ['nullable', 'boolean']],
    ],
    'projects' => [
        'title' => 'Projects',
        'subtitle' => 'Master proyek konstruksi',
        'group' => 'Project',
        'icon' => 'bi-building',
        'model' => RefProject::class,
        'route' => 'master.projects',
        'display' => 'project_name',
        'columns' => [['key' => 'project_code', 'label' => 'Project Code'], ['key' => 'project_name', 'label' => 'Project Name'], ['key' => 'owner_name', 'label' => 'Owner'], ['key' => 'status', 'label' => 'Project Status'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['project_code' => ['type' => 'text', 'label' => 'Project Code'], 'project_name' => ['type' => 'text', 'label' => 'Project Name', 'span' => 2], 'owner_name' => ['type' => 'text', 'label' => 'Owner Name'], 'start_date' => ['type' => 'date', 'label' => 'Start Date'], 'end_date' => ['type' => 'date', 'label' => 'End Date'], 'contract_value' => ['type' => 'number', 'label' => 'Contract Value', 'step' => '0.01'], 'status' => ['type' => 'select_static', 'label' => 'Status', 'options' => ['planning' => 'Planning', 'running' => 'Running', 'completed' => 'Completed', 'on_hold' => 'On Hold']], 'description' => $description, 'is_active' => $active],
        'rules' => ['project_code' => ['required', 'string', 'max:50', 'unique:ref_project,project_code,{id}'], 'project_name' => ['required', 'string', 'max:180'], 'owner_name' => ['nullable', 'string', 'max:180'], 'start_date' => ['nullable', 'date'], 'end_date' => ['nullable', 'date', 'after_or_equal:start_date'], 'contract_value' => ['nullable', 'numeric', 'min:0'], 'status' => ['required', 'string', 'max:50'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'project-sites' => [
        'title' => 'Project Sites',
        'subtitle' => 'Lokasi/site per proyek',
        'group' => 'Project',
        'icon' => 'bi-geo-alt',
        'model' => RefProjectSite::class,
        'route' => 'master.project-sites',
        'with' => ['project'],
        'display' => 'site_name',
        'columns' => [['key' => 'project.project_name', 'label' => 'Project'], ['key' => 'site_code', 'label' => 'Site Code'], ['key' => 'site_name', 'label' => 'Site Name'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['project_id' => ['type' => 'select', 'label' => 'Project', 'relation' => 'projects'], 'site_code' => ['type' => 'text', 'label' => 'Site Code'], 'site_name' => ['type' => 'text', 'label' => 'Site Name', 'span' => 2], 'address' => ['type' => 'textarea', 'label' => 'Address', 'span' => 2], 'is_active' => $active],
        'rules' => ['project_id' => ['required', 'exists:ref_project,id'], 'site_code' => ['required', 'string', 'max:50'], 'site_name' => ['required', 'string', 'max:180'], 'address' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'cost-codes' => [
        'title' => 'Cost Codes',
        'subtitle' => 'Struktur hirarki kode biaya',
        'group' => 'Project',
        'icon' => 'bi-diagram-3',
        'model' => RefCostCode::class,
        'route' => 'master.cost-codes',
        'with' => ['parent', 'project'],
        'display' => 'name',
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name'], ['key' => 'parent.name', 'label' => 'Parent'], ['key' => 'project.project_name', 'label' => 'Project'], ['key' => 'level', 'label' => 'Level'], ['key' => 'type', 'label' => 'Type'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['parent_id' => ['type' => 'select', 'label' => 'Parent Cost Code', 'relation' => 'cost-codes', 'nullable' => true], 'project_id' => ['type' => 'select', 'label' => 'Project', 'relation' => 'projects', 'nullable' => true], 'code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'level' => ['type' => 'number', 'label' => 'Level'], 'type' => ['type' => 'select_static', 'label' => 'Type', 'options' => ['material' => 'Material', 'labor' => 'Labor', 'equipment' => 'Equipment', 'subcontract' => 'Subcontract', 'overhead' => 'Overhead']], 'description' => $description, 'is_active' => $active],
        'rules' => ['parent_id' => ['nullable', 'exists:ref_cost_codes,id'], 'project_id' => ['nullable', 'exists:ref_project,id'], 'code' => ['required', 'string', 'max:80'], 'name' => ['required', 'string', 'max:180'], 'level' => ['required', 'integer', 'min:1'], 'type' => ['required', 'string', 'max:50'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'vendor-types' => [
        'title' => 'Vendor Types',
        'subtitle' => 'Klasifikasi vendor',
        'group' => 'Vendor',
        'icon' => 'bi-bookmark',
        'model' => RefVendorType::class,
        'route' => 'master.vendor-types',
        'display' => 'name',
        'columns' => [['key' => 'code', 'label' => 'Code'], ['key' => 'name', 'label' => 'Name'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['code' => ['type' => 'text', 'label' => 'Code'], 'name' => ['type' => 'text', 'label' => 'Name', 'span' => 2], 'description' => $description, 'is_active' => $active],
        'rules' => ['code' => ['required', 'string', 'max:50', 'unique:ref_vendor_type,code,{id}'], 'name' => ['required', 'string', 'max:150'], 'description' => ['nullable', 'string'], 'is_active' => ['nullable', 'boolean']],
    ],
    'vendors' => [
        'title' => 'Vendors',
        'subtitle' => 'Master rekanan dan supplier konstruksi',
        'group' => 'Vendor',
        'icon' => 'bi-truck',
        'model' => RefVendor::class,
        'route' => 'master.vendors',
        'with' => ['type'],
        'display' => 'vendor_name',
        'columns' => [['key' => 'vendor_code', 'label' => 'Vendor Code'], ['key' => 'vendor_name', 'label' => 'Vendor Name'], ['key' => 'type.name', 'label' => 'Type'], ['key' => 'phone', 'label' => 'Phone'], ['key' => 'email', 'label' => 'Email'], ['key' => 'is_active', 'label' => 'Status', 'type' => 'status']],
        'fields' => ['vendor_type_id' => ['type' => 'select', 'label' => 'Vendor Type', 'relation' => 'vendor-types'], 'vendor_code' => ['type' => 'text', 'label' => 'Vendor Code'], 'vendor_name' => ['type' => 'text', 'label' => 'Vendor Name', 'span' => 2], 'npwp' => ['type' => 'text', 'label' => 'NPWP'], 'address' => ['type' => 'textarea', 'label' => 'Address', 'span' => 2], 'phone' => ['type' => 'text', 'label' => 'Phone'], 'email' => ['type' => 'email', 'label' => 'Email'], 'pic_name' => ['type' => 'text', 'label' => 'PIC Name'], 'bank_name' => ['type' => 'text', 'label' => 'Bank Name'], 'bank_account' => ['type' => 'text', 'label' => 'Bank Account'], 'is_active' => $active],
        'rules' => ['vendor_type_id' => ['required', 'exists:ref_vendor_type,id'], 'vendor_code' => ['required', 'string', 'max:50', 'unique:ref_vendor,vendor_code,{id}'], 'vendor_name' => ['required', 'string', 'max:180'], 'npwp' => ['nullable', 'string', 'max:50'], 'address' => ['nullable', 'string'], 'phone' => ['nullable', 'string', 'max:50'], 'email' => ['nullable', 'email', 'max:150'], 'pic_name' => ['nullable', 'string', 'max:150'], 'bank_name' => ['nullable', 'string', 'max:120'], 'bank_account' => ['nullable', 'string', 'max:120'], 'is_active' => ['nullable', 'boolean']],
    ],
];
